trikey:

  # Settings for ros_control control loop
  hw_control_loop:
    loop_hz: 1000
    cycle_time_error_threshold: 0.01

  # Settings for ros_control hardware interface, enc_counts should be [10000, 10000, 8300]
  hardware_interface:
    joints: [wheel0_joint, wheel1_joint, wheel2_joint]
    interface_name: enp1s0
    #    wheel_encoder_counts: [10000, 10000, 8300]
    wheel_encoder_counts: [8500, 8500, 8350]
    wheel_encoder_sign: [-1, -1, -1]

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500

  # Position Controllers ---------------------------------------
  wheel0_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel0_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wheel1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wheel2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
